#!/usr/bin/env python3
from pathlib import Path
import json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(name,cond,detail=''):
    checks.append({'name':name,'passed':bool(cond),'detail':str(detail)})
    print(('OK' if cond else 'FALHA'),'-',name,detail)
def text(rel): return (ROOT/rel).read_text('utf-8')
version=json.loads(text('VERSION.json'))
avatar=text('src/modules/34-avatar-studio-professional-v3.js')
npc=text('src/modules/13-houses-npcs-vehicles-base.js')
gm=text('src/modules/39-gm-admin-panel.js')
rtdb=text('assets/js/multiplayer-rtdb.js')
rules=text('firebase-database.rules.json')
sports=text('src/modules/13a-sports-kart-v705.js')
races=text('src/modules/21-interactions-shop-social-races.js')
style=text('src/styles/19-mobile-landscape-authority-v7051.css')
check('Release R11 ativa',int(version.get('assetVersion',0))>=70581 and 'r11' in str(version.get('release','')).lower())
check('Playmobil possui olhos fora da cabeça',"theme==='playmobil'" in avatar and '.585' in avatar and '.592' in avatar)
check('Playmobil NPC possui rosto na superfície','.425' in npc and '.432' in npc)
check('Mario aparece como opção explícita',"['mario-world','Mario World — Mario','🧢']" in avatar)
check('Luigi aparece como opção explícita',"['luigi-world','Mario World — Luigi','🟢']" in avatar)
check('Mario e Luigi possuem emblema M/L',"isLuigi?'L':'M'" in avatar and 'MARIO_EMBLEM' in avatar and 'LUIGI_EMBLEM' in avatar)
check('Mario/Luigi usam jardineira azul','marioOveralls' in avatar and '0x245db2' in avatar)
check('GM oferece bloquear usuário','data-gm-block' in gm and 'gmSetUserBlocked' in rtdb)
check('GM oferece desbloquear usuário','data-gm-unblock' in gm and 'gmSetUserBlocked' in rtdb)
check('GM oferece excluir usuário e dados','data-gm-delete-user' in gm and 'gmDeleteUserData' in rtdb)
check('GM não permite automoderação','A conta GM atual não pode ser bloqueada ou excluída' in rtdb)
check('Outra conta GM é protegida','Outra conta GM não pode ser moderada' in rtdb)
check('Bloqueio não apaga cadastro','gmRemoveUserFromRooms(f,targetUid,updates,false)' in rtdb)
check('Exclusão apaga cadastro e gameAccount',"updates[`users/${targetUid}`]=null" in rtdb and "updates[`gameAccounts/${targetUid}`]=null" in rtdb)
check('Exclusão mantém tombstone deleted',"state:'deleted'" in rtdb and 'moderationPath(targetUid)' in rtdb)
check('Cliente checa moderação no login','enforceAccountModeration' in rtdb and 'signInPlayerAccount' in rtdb)
check('Regras possuem userModeration','"userModeration"' in rules and "state').val() === 'blocked'" in rules)
check('Cliente bloqueia conta moderada antes da conexão', 'const moderation=await enforceAccountModeration(f,user);if(!moderation.ok)throw new Error(moderation.error)' in rtdb)
check('Botão sair da partida existe','data-sport-exit' in sports and "textContent='✕ Sair'" in sports)
check('Saída é exposta na API de esportes','leave:leaveCurrentSportV705' in sports)
check('Atletismo também exibe saída',"ensureSportExitButton(true)" in races)
check('Saída de atletismo não chama finishRace','clearRaceObjects();activeRace=null' in sports)
check('Saída não incrementa derrota ou vitória','leaveCurrentSportV705' in sports and 'state.races.losses++' not in re.search(r'function leaveCurrentSportV705\(\)\{.*?\n  \}',sports,re.S).group(0))
check('Saída de kart preserva veículo','if(kartActive&&player.vehicle)player.car.speed=0' in sports and 'exitVehicle' not in re.search(r'function leaveCurrentSportV705\(\)\{.*?\n  \}',sports,re.S).group(0))
check('Botão sair é clicável no HUD','.race-badge.has-sport-exit{pointer-events:auto' in style and '.sport-exit-btn' in style)
for rel in ['src/modules/34-avatar-studio-professional-v3.js','src/modules/39-gm-admin-panel.js','src/modules/13a-sports-kart-v705.js','src/modules/21-interactions-shop-social-races.js','assets/js/multiplayer-rtdb.js']:
    result=subprocess.run(['node','--check',rel],cwd=ROOT,capture_output=True,text=True)
    check(f'Sintaxe válida: {rel}',result.returncode==0,result.stderr.strip()[:500])
failed=[x for x in checks if not x['passed']]
print(json.dumps({'passed':not failed,'counts':{'passed':len(checks)-len(failed),'failed':len(failed),'total':len(checks)},'failed':failed},ensure_ascii=False,indent=2))
sys.exit(1 if failed else 0)
